Update GCR tag and push location
paketo-buildpacks/base-builder pull request #16
Opened 2020-11-03 20:58 UTC by thitch97

- Add GHA step to push to Dockerhub

2020-11-03 21:03 UTC, fg-j commented
Also pushes base builder to the `:latest` tag per [builder RFC #4](https://github.com/paketo-buildpacks/builder/pull/42).

2020-11-05 17:08 UTC, dumez-k requested changes

2020-11-05 17:08 UTC, dumez-k commented on .github/workflows/push-image.yml
> +        docker tag builder "gcr.io/paketo-buildpacks/builder:base-platform-api-0.3"
as we don't publish different versions per lifecycle version anymore this tag can be removed

2020-11-05 17:08 UTC, dumez-k commented on .github/workflows/push-image.yml
> +
is there a reason that we don't have the `bionic` tag anymore?
@ekcasey are you more familiar with the implications of removing it? want to avoid breaking anyone who relies on this tag.

2020-11-05 18:55 UTC, fg-j commented on .github/workflows/push-image.yml
> +        docker tag builder "gcr.io/paketo-buildpacks/builder:base-platform-api-0.3"
afaik that tag was [specifically requested](https://github.com/paketo-buildpacks/base-builder/issues/2) for Spring Boot compatibility

2020-11-09 16:37 UTC, ekcasey commented on .github/workflows/push-image.yml
> +        docker tag builder "gcr.io/paketo-buildpacks/builder:base-platform-api-0.3"
It is important that we continue to update `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3` until Spring Boot 2.3.x EOL, which extrapolating from previous support windows, I guess will be sometime around May 2022.

https://github.com/spring-projects/spring-boot/wiki/Supported-Versions

2020-11-09 17:06 UTC, ekcasey commented on .github/workflows/push-image.yml
> +
The only tag that a released version of Spring Boot depends on is
`gcr.io/paketo-buildpacks/builder:base-platform-api-0.3`. The next release will depend on `paketobuildpacks/builder:base`.

I am not aware of anyone specifically depending on the `bionic` tag. However the fact that we release and document these tags publically means that we generally won't know the full set of folks who are using them. I think we should drop the `bionic` tag but try hard to avoid changes to the tag names in the future.

2020-11-09 17:07 UTC, ekcasey approved these changes

2020-11-10 18:40 UTC, dumez-k approved these changes

2020-11-10 18:41 UTC, merged